export const browserCoreExamples = [
  "genesis browser status",
  "genesis browser start",
  "genesis browser stop",
  "genesis browser tabs",
  "genesis browser open https://example.com",
  "genesis browser focus abcd1234",
  "genesis browser close abcd1234",
  "genesis browser screenshot",
  "genesis browser screenshot --full-page",
  "genesis browser screenshot --ref 12",
  "genesis browser snapshot",
  "genesis browser snapshot --format aria --limit 200",
  "genesis browser snapshot --efficient",
  "genesis browser snapshot --labels",
];

export const browserActionExamples = [
  "genesis browser navigate https://example.com",
  "genesis browser resize 1280 720",
  "genesis browser click 12 --double",
  'genesis browser type 23 "hello" --submit',
  "genesis browser press Enter",
  "genesis browser hover 44",
  "genesis browser drag 10 11",
  "genesis browser select 9 OptionA OptionB",
  "genesis browser upload /tmp/genesis/uploads/file.pdf",
  'genesis browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "genesis browser dialog --accept",
  'genesis browser wait --text "Done"',
  "genesis browser evaluate --fn '(el) => el.textContent' --ref 7",
  "genesis browser console --level error",
  "genesis browser pdf",
];
